---
baseurl: "/Newberry-Italian-paleography"
collections:
  background_essay:
    output: true
    permalink: /essay/:name
  page:
    output: true
    permalink: /:slug
  transcriptions:
    output: true
    permalink: /:collection/:name
