---
baseurl: "/"
logo: "https://centerfordigitalhumanities.github.io/Newberry-paleography/images/slu_ovpr.png"
collections:
  background_essay:
    output: true
    permalink: /essay/:name
  page:
    output: true
    permalink: /:slug
  transcriptions:
    output: true
    permalink: /transcription/:name
